services:
  nginx:
    restart: always
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
       - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    restart: always
    build: ./srcs/wordpress
    container_name: wordpress
    environment:
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      WP_USER2: ${WP_USER2}
      WP_PASSWORD2: ${WP_PASSWORD2}
      WP_EMAIL2: ${WP_EMAIL2}
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "9000"

  mariadb:
    restart: always
    build: ./srcs/mariadb
    container_name: mariadb
    environment:
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql 

networks:
  inception:
    driver: bridge

volumes:
   wordpress_data:
     driver: local
     driver_opts:
       type: none
       o: bind
       device: /home/jmouline/data/wordpress
   mariadb_data:
     driver: local
     driver_opts:
       type: none
       o: bind
       device: /home/jmouline/data/mariadb